apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wm4mfnh3h-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wm4mfnh3h-go 
  name: wm4mfnh3h-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wm4mfnh3h-go 
